version: "3.9"

volumes:
  xxx-postgres-data:
  xxx-redis-data:
  
services:
  app:
    container_name: app-${APP_NAME}
    image: xxxxxx:latest
    build:
      context: .
      target: prod
    env_file:
      - .env
    ports: 
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

# Kalau DB eksternal → hapus service postgres
  postgres:
    container_name: postgres-${APP_NAME}
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - xxx-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    container_name: redis-${APP_NAME}
    image: redis:8
    restart: unless-stopped
    volumes:
      - xxx-redis-data:/data
      - ./src/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10